export const estudo = {
  key: "estudo",
  label: "Estudo",
  icon: "📚",
  color: "#60a5fa",
  description: "Aprendizado, cursos, leituras, idiomas",
  keywords: [
    "estudei", "estudar", "estudo", "estudei sobre", "estudei para",
    "li", "ler", "leitura", "livro", "livros", "capitulo", "capitulos", "paginas", "pagina",
    "curso", "cursos", "aula", "aulas", "videoaula", "video aula",
    "ingles", "espanhol", "frances", "alemao", "italiano", "japones", "mandarim",
    "idioma", "idiomas", "duolingo", "anki", "flashcard", "flashcards",
    "faculdade", "universidade", "escola", "mestrado", "doutorado", "graduacao",
    "tutorial", "tutoriais", "documentacao", "docs",
    "podcast", "podcasts", "audiobook", "audiolivro",
    "exercicio de", "lista de exercicios", "prova", "redacao", "questao", "questoes",
    "aprendi", "aprender", "aprendizado", "aprendizagem",
    "pesquisei", "pesquisa", "pesquisar",
    "udemy", "coursera", "alura", "khan academy", "edx",
    "certificacao", "certificado",
    "resumi", "resumir", "resumo",
    "anotei", "anotacao", "anotacoes", "fichamento",
    "kindle", "ebook",
    "matematica", "fisica", "quimica", "biologia", "historia", "geografia", "filosofia",
    "concurso", "vestibular", "enem",
    "tese", "monografia", "tcc",
    "professor", "professora", "mentor", "mentoria",
    "li sobre", "fiz curso", "terminei o curso", "concluí curso", "concluí o curso",
    "memorizei", "memorizar"
  ]
};
