export const financeiro = {
  key: "financeiro",
  label: "Financeiro",
  icon: "💰",
  color: "#f59e0b",
  description: "Economia, investimentos, gastos, conquistas financeiras",
  keywords: [
    "investi", "investimento", "investimentos", "investir", "investidor",
    "aporte", "aportei", "aportar",
    "acoes", "fundo", "fundos", "tesouro", "cdb", "lci", "lca",
    "fii", "fundos imobiliarios", "etf",
    "bolsa de valores", "b3",
    "criptomoeda", "cripto", "bitcoin", "btc", "ethereum",
    "comprei", "compra", "vendi", "venda",
    "economizei", "economia", "poupanca", "poupei", "poupar",
    "gastei", "gasto", "gastos", "despesa", "despesas",
    "salario", "recebi salario", "recebimento", "recebi",
    "pagamento", "paguei", "pagar", "boleto", "fatura",
    "cartao de credito", "cartao", "credito", "debito", "pix",
    "banco", "conta bancaria", "conta corrente", "conta poupanca",
    "orcamento", "planilha financeira", "controle financeiro", "controlei gastos",
    "dividendos", "dividendo", "rendimento", "rendeu", "lucro",
    "renda passiva", "renda extra", "renda fixa", "renda variavel",
    "imposto", "imposto de renda", "ir", "declaracao",
    "previdencia",
    "reserva de emergencia", "reserva financeira",
    "meta financeira", "objetivo financeiro",
    "endividamento", "divida", "dividas",
    "quitei", "quitacao",
    "emprestimo", "financiamento",
    "transferi", "transferencia", "depositei", "deposito", "saquei", "saque",
    "aluguel", "imovel",
    "cashback", "milhas", "pontos", "desconto",
    "doei", "doacao",
    "extrato", "fluxo de caixa", "patrimonio",
    "financeiro", "financas", "dinheiro", "grana"
  ]
};
