export const lazer = {
  key: "lazer",
  label: "Lazer",
  icon: "🎮",
  color: "#fbbf24",
  description: "Diversão, descanso, hobbies, entretenimento",
  keywords: [
    "filme", "filmes", "assisti", "cinema", "fui ao cinema",
    "serie", "series", "netflix", "prime", "disney", "hbo", "max", "globoplay",
    "documentario", "anime", "mangá", "kdrama",
    "jogo", "joguei", "jogar", "playstation", "xbox", "switch", "steam", "videogame",
    "boardgame", "rpg", "tabuleiro", "baralho", "cartas",
    "musica", "ouvi musica", "ouvi", "playlist", "spotify", "deezer",
    "toquei", "violao", "guitarra", "piano", "bateria", "instrumento",
    "cantei", "cantar", "karaoke",
    "dancei", "danca", "dancar",
    "passeio", "passear", "parque", "praia", "piscina",
    "viagem", "viajei", "viajar", "fui viajar",
    "festa", "churrasco", "bar", "balada", "show", "festival",
    "barzinho", "boteco", "evento",
    "hobby", "lazer", "diversao", "diverti",
    "desenhei", "pintei", "fotografei", "foto", "fotos",
    "relaxei", "relaxar", "ficar de boa", "descontrair",
    "piquenique", "pic nic",
    "camping", "acampamento", "acampei",
    "clube",
    "fim de semana", "feriado", "folga",
    "role", "saidinha"
  ]
};
