export const profissional = {
  key: "profissional",
  label: "Profissional",
  icon: "💼",
  color: "#34d399",
  description: "Trabalho, projetos, realizações profissionais",
  keywords: [
    "trabalho", "trabalhei", "trabalhar", "expediente",
    "projeto", "projetos", "entrega", "entreguei", "deliverable", "entregavel",
    "pr", "pull request", "merge", "merged", "code review", "review",
    "pr aprovado", "pr mergeado", "merge do pr", "fiz code review",
    "deploy", "deployei", "release", "lancei", "shipei", "subi pra producao",
    "deploy em prod", "deploy em producao", "producao", "homologacao", "qa",
    "reuniao", "reunioes", "meeting", "daily", "1:1", "one on one", "1on1",
    "stand up", "standup", "all hands", "town hall",
    "sprint", "planning", "retro", "retrospectiva", "kickoff", "grooming", "refinamento",
    "ticket", "tickets", "jira", "linear", "trello", "kanban", "asana",
    "issue", "issues",
    "cliente", "clientes", "stakeholder", "reuniao com cliente",
    "apresentacao", "apresentei", "demo", "talk", "palestra",
    "bug", "bugs", "bugfix", "fix", "corrigi", "corrigir",
    "feature", "features", "funcionalidade",
    "codigo", "codei", "programei", "implementei",
    "refatorei", "refactor", "refatoracao",
    "documentei", "documentacao do projeto", "documentacao tecnica",
    "debug", "debuggei", "investiguei",
    "carreira", "promocao", "promovido", "feedback", "performance review",
    "networking", "linkedin", "entrevista",
    "okr", "okrs", "kpi", "metas", "meta do trimestre",
    "ci", "ci cd", "pipeline", "build verde", "build quebrou",
    "incidente", "postmortem", "rollback",
    "rodei testes", "testes", "lint", "linter", "type check",
    "monitoramento", "logs", "metric", "metricas", "dashboard",
    "freelance", "freela", "side project",
    "github", "gitlab", "bitbucket", "branch", "rebase", "commit", "commits",
    "automacao", "implantei", "implantar",
    "negociei", "fechei contrato", "proposta",
    "spike", "epic", "story", "user story"
  ]
};
