export const saude = {
  key: "saude",
  label: "Saúde",
  icon: "🏃",
  color: "#4ade80",
  description: "Exercícios, alimentação, bem-estar físico e mental",
  keywords: [
    "corri", "correr", "corrida", "caminhada", "caminhei", "caminhar",
    "academia", "treino", "treinei", "treinar", "musculacao", "malhei", "malhar",
    "exercicio", "exercicios", "yoga", "pilates", "alongamento", "alongar", "alonguei",
    "natacao", "nadei", "nadar", "bicicleta", "pedalei", "pedalar", "pedalada",
    "respiracao", "respirei", "respirar",
    "crossfit", "funcional", "spinning", "zumba", "muay thai", "jiu jitsu", "boxe", "luta", "lutei",
    "hiit", "cardio", "musculo",
    "passos", "andei", "andar", "trilha", "trilhei",
    "skate", "patins", "patinar",
    "alimentacao saudavel", "salada", "fruta", "frutas", "verdura", "verduras",
    "dieta", "jejum", "jejum intermitente",
    "proteina", "vitamina", "vitaminas",
    "agua", "hidratei", "hidratei me", "hidratacao", "tomei agua",
    "dormi cedo", "soneca", "descansei", "descanso", "sono", "noite de sono",
    "saude", "medico", "dentista", "consulta", "exame", "exames", "remedio", "remedios",
    "terapia", "psicologa", "psicologo", "psiquiatra",
    "nutricionista", "checkup", "vacina", "vacinei",
    "fisioterapia", "fisio", "massagem", "sauna",
    "perdi peso", "ganhei massa", "balanca",
    "postura", "saude mental",
    "fui correr", "fui na academia", "fui pra academia", "treino de"
  ]
};
